spring:
  datasource:
    url: jdbc:mysql://enrollment-db:3306/enrollment_db
    username: enrollment_user
    password: enrollment_pass
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

user-service:
  url: http://user-service:8081
catalog-service:
  url: http://catalog-service:8082

logging:
  level:
    com.zjgsu.lyy.enrollment: INFO