spring:
  datasource:
    url: jdbc:mysql://catalog-db:3306/catalog_db
    username: catalog_user
    password: catalog_pass
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

logging:
  level:
    com.zjgsu.lyy.catalog: INFO