spring:
  datasource:
    url: jdbc:mysql://user-db:3306/user_db
    username: user_user
    password: user_pass
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

logging:
  level:
    com.zjgsu.lyy.user_service: INFO